# Generated by Django 5.2.7 on 2025-10-25 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('assistant_pi', 'Assistant Principal Investigator'), ('research_assistant', 'Research Assistant'), ('graduate_student', 'Graduate Student'), ('alumni', 'Alumni')], max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
