# Generated by Django 5.2.7 on 2025-10-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_userprofile_affiliation_userprofile_bibliography_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationauthor',
            options={'ordering': ['sequence', 'id']},
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('principal_investigator', 'Principal Investigator'), ('assistant_pi', 'Assistant Principal Investigator'), ('research_assistant', 'Research Assistant'), ('graduate_student', 'Graduate Student'), ('alumni', 'Alumni')], max_length=32),
        ),
    ]
