# Generated by Django 5.2.7 on 2025-10-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_publicationauthor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='book_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
