# Generated by Django 5.2.7 on 2025-10-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_publication_book_title_publication_journal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='research_area',
            field=models.CharField(blank=True, choices=[('computer_vision', 'Computer Vision'), ('medical_image_analysis', 'Medical Image Analysis'), ('remote_sensing', 'Remote Sensing'), ('computational_biology_bioinformatics', 'Computational Biology and Bioinformatics'), ('image_processing', 'Image Processing')], max_length=64),
        ),
    ]
