# Generated by Django 5.2.7 on 2025-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_experience_description_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('affiliation', 'Professional Affiliation')], default='work', max_length=20),
        ),
    ]
