# Generated by Django 5.2.7 on 2025-10-25 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_experience_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoauthorSyncRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sync_requests', to=settings.AUTH_USER_MODEL)),
                ('source_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_requests', to='lab.publication')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthor_sync_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('source_publication', 'target_user')},
            },
        ),
    ]
