# Generated by Trae AI on demand: create default super admin with forced password change
from django.db import migrations

def create_super_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('lab', 'UserProfile')

    # Create default super admin if not exists
    if not User.objects.filter(username='admin').exists():
        user = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='Admin@VIP1234',
        )
        # Ensure profile exists with required defaults
        profile, created = UserProfile.objects.get_or_create(
            user_id=user.id,
            defaults={
                'organization': '',
                'department': '',
                'role': 'principal_investigator',
                'must_change_password': True,
                'display_order': 0,
            }
        )
        if not created:
            # Mark force change password
            profile.must_change_password = True
            profile.save(update_fields=['must_change_password'])

class Migration(migrations.Migration):
    dependencies = [
        ('lab', '0009_publication_display_order_userprofile_display_order_and_more'),
    ]

    operations = [
        migrations.RunPython(create_super_admin),
    ]