# Generated by Django 5.2.7 on 2025-10-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_default_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='show_on_public_pages',
            field=models.BooleanField(default=True),
        ),
    ]
