# Generated by Django 5.2.7 on 2025-10-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_backfill_publication_research_areas'),
        ('lab', '0020_userprofile_professional_summary'),
    ]

    operations = [
    ]
